# Generated by Django 5.1.2 on 2024-10-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0002_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantbuilding',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
