# Generated by Django 5.1.2 on 2026-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0003_vacantbuilding_latitude_vacantbuilding_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantbuilding',
            name='facility_size',
            field=models.CharField(blank=True, choices=[('15_40', '15–40 m²'), ('40_100', '40–100 m²'), ('100_200', '100–200 m²'), ('over_200', '>200 m²')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='governance',
            field=models.CharField(blank=True, choices=[('civil_society', 'Civil society organisations'), ('public', 'Public'), ('private', 'Private'), ('mixed', 'Mixed or other models')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='previous_state',
            field=models.CharField(blank=True, choices=[('poor', 'Poor'), ('moderate', 'Moderate'), ('excellent', 'Excellent')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='previous_use',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('industry', 'Industry'), ('gastronomy', 'Gastronomy'), ('small_retail', 'Small retail space'), ('large_retail', 'Large retail space')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='reachability',
            field=models.CharField(blank=True, choices=[('very_central', 'Very Central'), ('central', 'Central'), ('somewhat_central', 'Somewhat Central'), ('not_central', 'Not centrally located')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='type_of_use',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('long_term', 'Long-term'), ('permanent', 'Permanent')], max_length=20, null=True),
        ),
    ]
