# Generated by Django 5.1.2 on 2026-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0004_vacantbuilding_facility_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractice',
            name='factsheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factsheets/best_practices/'),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='factsheet_pdf_de',
            field=models.FileField(blank=True, null=True, upload_to='factsheets/vacant_buildings/de/'),
        ),
        migrations.AddField(
            model_name='vacantbuilding',
            name='factsheet_pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='factsheets/vacant_buildings/en/'),
        ),
    ]
