# Generated by Django 5.1.2 on 2026-02-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0005_bestpractice_factsheet_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantbuilding',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vacantbuilding',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
