# Generated by Django 5.1.2 on 2026-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0007_populate_factsheet_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractice',
            name='factsheet_pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='factsheets/best_practices/'),
        ),
    ]
