# Generated by Django 5.1.2 on 2026-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_app', '0012_update_factsheet_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpractice',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
